-- =============================================================================
-- 15_observability_integration.sql — External Data Observability Setup
-- Data Vault 2.0 Snowflake Data Platform
--
-- PURPOSE: Configure Snowflake for external data observability tools
--          (Monte Carlo, Metaplane, Validio) with least-privilege access.
--
-- FEATURES:
--   - Dedicated observability service account (read-only)
--   - Native Snowflake Event Table for structured error logging
--   - Error handling procedures with TRY...CATCH patterns
--   - Monte Carlo / Metaplane connection prerequisites
--
-- EXECUTION ORDER: Run AFTER all databases and schemas are created
-- REQUIRES: ACCOUNTADMIN
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- 1. OBSERVABILITY SERVICE ACCOUNT (Read-Only for Monte Carlo / Metaplane)
-- =============================================================================

CREATE USER IF NOT EXISTS OBSERVABILITY_SVC_USER
    DEFAULT_ROLE = 'OBSERVABILITY_READER'
    DEFAULT_WAREHOUSE = 'DEV_WH'
    COMMENT = 'Read-only service account for data observability tools (Monte Carlo / Metaplane)'
    MUST_CHANGE_PASSWORD = FALSE;

CREATE ROLE IF NOT EXISTS OBSERVABILITY_READER
    COMMENT = 'Least-privilege read-only role for observability tools';

-- Grant OBSERVABILITY_READER → SYSADMIN hierarchy
GRANT ROLE OBSERVABILITY_READER TO ROLE SYSADMIN;

-- Read access to all data databases
GRANT USAGE ON DATABASE RAW_VAULT TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON DATABASE BUSINESS_VAULT TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON DATABASE AUDIT TO ROLE OBSERVABILITY_READER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_VAULT TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BUSINESS_VAULT TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE OBSERVABILITY_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUDIT TO ROLE OBSERVABILITY_READER;

GRANT SELECT ON ALL TABLES IN DATABASE RAW_VAULT TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON ALL TABLES IN DATABASE BUSINESS_VAULT TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON ALL TABLES IN DATABASE AUDIT TO ROLE OBSERVABILITY_READER;

-- Future grants for auto-coverage of new tables
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_VAULT TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE BUSINESS_VAULT TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE AUDIT TO ROLE OBSERVABILITY_READER;

-- ACCOUNT_USAGE access (required for observability tools)
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE OBSERVABILITY_READER;

-- Assign role to service account
GRANT ROLE OBSERVABILITY_READER TO USER OBSERVABILITY_SVC_USER;

-- =============================================================================
-- 2. NATIVE EVENT TABLE — Structured Error Logging
-- =============================================================================

CREATE EVENT TABLE IF NOT EXISTS AUDIT.CONTROL.PLATFORM_EVENT_LOG
    CLUSTER BY (RESOURCE_ATTRIBUTES['snow.executable.name'])
    DATA_RETENTION_TIME_IN_DAYS = 365
    COMMENT = 'Native Snowflake Event Table — structured error/warning/info logging from procedures and tasks';

-- Set as account-level event table
ALTER ACCOUNT SET EVENT_TABLE = AUDIT.CONTROL.PLATFORM_EVENT_LOG;

-- =============================================================================
-- 3. ERROR EVENT LOG — Custom Error Tracking Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS AUDIT.CONTROL.ERROR_EVENT_LOG (
    ERROR_ID                VARCHAR(64)     DEFAULT UUID_STRING() NOT NULL,
    ERROR_TIMESTAMP         TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PROCEDURE_NAME          VARCHAR(500)    NOT NULL,
    ERROR_CODE              VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000)   NOT NULL,
    ERROR_STATE             VARCHAR(20),
    STACK_TRACE             VARCHAR(8000),
    INPUT_PARAMETERS        VARIANT,
    SEVERITY                VARCHAR(20)     DEFAULT 'ERROR', -- DEBUG | INFO | WARNING | ERROR | CRITICAL
    RESOLUTION_STATUS       VARCHAR(20)     DEFAULT 'OPEN',  -- OPEN | ACKNOWLEDGED | RESOLVED
    RESOLVED_BY             VARCHAR(250),
    RESOLVED_AT             TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ERROR_EVENT_LOG PRIMARY KEY (ERROR_ID)
)
CLUSTER BY (PROCEDURE_NAME, ERROR_TIMESTAMP)
COMMENT = 'Centralized error event log — TRY...CATCH exceptions from all procedures and tasks';

GRANT SELECT, INSERT ON TABLE AUDIT.CONTROL.ERROR_EVENT_LOG TO ROLE TRANSFORMER;
GRANT SELECT, INSERT ON TABLE AUDIT.CONTROL.ERROR_EVENT_LOG TO ROLE DATA_ENGINEER;
GRANT SELECT ON TABLE AUDIT.CONTROL.ERROR_EVENT_LOG TO ROLE PLATFORM_ADMIN;

-- =============================================================================
-- 4. CENTRALIZED ERROR HANDLING PROCEDURE
-- =============================================================================

CREATE OR REPLACE PROCEDURE AUDIT.CONTROL.LOG_ERROR(
    PROC_NAME VARCHAR,
    ERR_CODE VARCHAR,
    ERR_MESSAGE VARCHAR,
    ERR_STATE VARCHAR,
    STACK_TRACE VARCHAR,
    INPUT_PARAMS VARIANT,
    SEVERITY VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    INSERT INTO AUDIT.CONTROL.ERROR_EVENT_LOG (
        PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, ERROR_STATE,
        STACK_TRACE, INPUT_PARAMETERS, SEVERITY
    )
    VALUES (
        :PROC_NAME, :ERR_CODE, :ERR_MESSAGE, :ERR_STATE,
        :STACK_TRACE, :INPUT_PARAMS, :SEVERITY
    );

    -- Also log to native Snowflake event table
    SYSTEM$LOG_ERROR('PROCEDURE=' || :PROC_NAME || ' CODE=' || :ERR_CODE || ' MSG=' || :ERR_MESSAGE);

    RETURN 'Error logged: ' || :ERR_CODE || ' — ' || :ERR_MESSAGE;
END;

GRANT USAGE ON PROCEDURE AUDIT.CONTROL.LOG_ERROR(
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARIANT, VARCHAR
) TO ROLE TRANSFORMER;

-- =============================================================================
-- 5. EXAMPLE: TRY...CATCH PATTERN FOR SNOWFLAKE PROCEDURES
-- =============================================================================

CREATE OR REPLACE PROCEDURE AUDIT.CONTROL.SAFE_INGESTION_CHECK(
    SOURCE_SYSTEM VARCHAR,
    MAX_AGE_HOURS NUMBER
)
RETURNS TABLE (STATUS VARCHAR, DETAIL VARCHAR, CHECKED_AT TIMESTAMP_NTZ)
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    result RESULTSET;
BEGIN
    result := (
        SELECT
            CASE
                WHEN DATEDIFF('hour', MAX(LOAD_START_TS), CURRENT_TIMESTAMP()) <= :MAX_AGE_HOURS
                    THEN 'HEALTHY'
                ELSE 'SLA_BREACH'
            END AS STATUS,
            'Last ingestion: ' || COALESCE(MAX(LOAD_START_TS)::VARCHAR, 'NEVER') AS DETAIL,
            CURRENT_TIMESTAMP() AS CHECKED_AT
        FROM AUDIT.CONTROL.FILE_INGESTION_LOG
        WHERE SOURCE_SYSTEM = :SOURCE_SYSTEM
    );

    RETURN TABLE(result);

EXCEPTION
    WHEN OTHER THEN
        -- Log the error to centralized error table
        CALL AUDIT.CONTROL.LOG_ERROR(
            'SAFE_INGESTION_CHECK',
            SQLCODE::VARCHAR,
            SQLERRM,
            SQLSTATE,
            '',
            OBJECT_CONSTRUCT('source_system', :SOURCE_SYSTEM, 'max_age_hours', :MAX_AGE_HOURS),
            'ERROR'
        );
        -- Return error status instead of crashing
        result := (SELECT 'ERROR' AS STATUS, SQLERRM AS DETAIL, CURRENT_TIMESTAMP() AS CHECKED_AT);
        RETURN TABLE(result);
END;

-- =============================================================================
-- 6. OBSERVABILITY MONITORING VIEWS
-- =============================================================================

-- Error trend view (for dashboards and alerting)
CREATE OR REPLACE VIEW AUDIT.CONTROL.ERROR_TREND_REPORT AS
SELECT
    DATE_TRUNC('hour', ERROR_TIMESTAMP) AS ERROR_HOUR,
    PROCEDURE_NAME,
    SEVERITY,
    COUNT(*) AS ERROR_COUNT,
    ARRAY_AGG(DISTINCT ERROR_CODE) AS ERROR_CODES
FROM AUDIT.CONTROL.ERROR_EVENT_LOG
WHERE ERROR_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3
ORDER BY ERROR_HOUR DESC, ERROR_COUNT DESC;

-- Data freshness SLA view (for Monte Carlo / Metaplane custom monitors)
CREATE OR REPLACE VIEW AUDIT.CONTROL.DATA_FRESHNESS_SLA AS
SELECT
    SOURCE_SYSTEM,
    COUNT(*) AS FILES_LOADED_24H,
    SUM(ROWS_LOADED) AS ROWS_LOADED_24H,
    MAX(LOAD_END_TS) AS LATEST_LOAD,
    DATEDIFF('minute', MAX(LOAD_END_TS), CURRENT_TIMESTAMP()) AS MINUTES_SINCE_LAST_LOAD,
    CASE
        WHEN DATEDIFF('hour', MAX(LOAD_END_TS), CURRENT_TIMESTAMP()) <= 12 THEN 'WITHIN_SLA'
        WHEN DATEDIFF('hour', MAX(LOAD_END_TS), CURRENT_TIMESTAMP()) <= 24 THEN 'WARNING'
        ELSE 'SLA_BREACH'
    END AS SLA_STATUS
FROM AUDIT.CONTROL.FILE_INGESTION_LOG
WHERE LOAD_START_TS >= DATEADD('day', -1, CURRENT_TIMESTAMP())
GROUP BY SOURCE_SYSTEM
ORDER BY LATEST_LOAD DESC;

GRANT SELECT ON VIEW AUDIT.CONTROL.ERROR_TREND_REPORT TO ROLE DATA_ENGINEER;
GRANT SELECT ON VIEW AUDIT.CONTROL.ERROR_TREND_REPORT TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON VIEW AUDIT.CONTROL.DATA_FRESHNESS_SLA TO ROLE DATA_ENGINEER;
GRANT SELECT ON VIEW AUDIT.CONTROL.DATA_FRESHNESS_SLA TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON VIEW AUDIT.CONTROL.DATA_FRESHNESS_SLA TO ROLE OBSERVABILITY_READER;
GRANT SELECT ON VIEW AUDIT.CONTROL.ERROR_TREND_REPORT TO ROLE OBSERVABILITY_READER;
